In [2]:
import torch

# einsum
torch.einsum(equation, *operands)<br>
공식홈페이지 : Sums the product of the elements of the input operands along dimensions specified using a notation based on the Einstein summation convention.

numpy, tensorflow에도 동일한 연산이 있음

equation은 inputs->output이며 각 tensor의 shape을 나타냄, inputs는 ","를 통해 여러 개를 구분함

In [22]:
def check(equation,  *matrix, input_print=True):
    if input_print:
        print('Before operating')
        for mat in matrix:
            print(mat)
    einsum = torch.einsum(equation, *matrix)
    print('After operating')
    print(einsum)

In [23]:
# 1개의 tensor에 대한 sum
test = (torch.rand(2,3)*20).int()
check('ij->', test)
# 행의 개수를 유지한채 반환되도록 행별로 더함
check('ij->i', test, input_print=False)
# 열의 개수를 유지한채 반환되로독 열별로 더함
check('ij->j', test, input_print=False)

Before operating
tensor([[ 5, 13,  5],
        [ 6, 14, 15]], dtype=torch.int32)
After operating
tensor(58)
After operating
tensor([23, 35])
After operating
tensor([11, 27, 20])


In [34]:
# 여러개의 tensor에 대한 
test1 = torch.Tensor([[0,1,2],[3,4,5]])
test2 = torch.Tensor([0,1,2])
check('ij, j->ij', test1, test2, input_print=True)
check('ij, j->i', test1, test2, input_print=False)
check('ik,kj->ij', test1, test1.T, input_print=True)

Before operating
tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([0., 1., 2.])
After operating
tensor([[ 0.,  1.,  4.],
        [ 0.,  4., 10.]])
After operating
tensor([ 5., 14.])
Before operating
tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[0., 3.],
        [1., 4.],
        [2., 5.]])
After operating
tensor([[ 5., 14.],
        [14., 50.]])
